on: [push, pull_request]

name: CI

jobs:

  build-test:
    name: Build and test
    runs-on: macos-10.15
    strategy:
      matrix:
        include:
          - target: x86_64-server-android
            test: true
            api: 28
            arch: x86_64
          - target: i686-server-android
            test: true
            api: 28
            arch: x86
          - target: aarch64-server-android
          - target: armv7-server-androideabi
    env:
      BUILD_TARGETS: ${{ matrix.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set default toolchain
        run: rustup default stable
      - name: Set profile
        run: rustup set profile minimal
      - name: Add target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: ./gradlew build
      - name: Test
        if: ${{ matrix.test == true }}
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api }}
          arch: ${{ matrix.arch }}
          script: ./gradlew connectedDebugAndroidTest

  build-all:
    name: Build all targets
    runs-on: ubuntu-18.04
    env:
      BUILD_TARGETS: aarch64,armv7,x86_64,i686
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set default toolchain
        run: rustup default stable
      - name: Set profile
        run: rustup set profile minimal
      - name: Add targets
        run: rustup target add x86_64-server-android i686-server-android aarch64-server-android armv7-server-androideabi
      - name: Build
        run: ./gradlew build

  rust-fmt:
    name: Rust fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set default toolchain
        run: rustup default ${{ matrix.rust }}
      - name: Set profile
        run: rustup set profile minimal
      - name: Add rustfmt
        run: rustup component add rustfmt
      - name: Check fmt
        run: cargo fmt --all -- --check